name: Build and Publish to TestPyPI

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # Возможность запуска вручную

permissions:
  id-token: write # Необходимо для Trusted Publishing (OIDC)

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # python-version: ["3.12", "3.13", "3.14"]
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tool
        run: pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/

      - name: Upload tests for testing
        uses: actions/upload-artifact@v4
        with:
          name: tests
          path: tests/

  test:
    name: Test installed wheel on ${{ matrix.os }}
    needs: [build]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        # python-version: ["3.12", "3.13", "3.14"]
        python-version: ["3.14"]

    steps:
      - name: Download tests artifact
        uses: actions/download-artifact@v4
        with:
          name: tests
          path: tests/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/

      - name: Install wheel into fresh environment
        run: |
          pip install dist/*.whl, pytest
        shell: bash

      - name: Run tests from a safe directory
        run: |
          python -m pytest /tests
        shell: bash

  publish-testpypi:
    name: Publish to TestPyPI
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - name: Download all dist artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-all/
          pattern: dist-*
          merge-multiple: true

      - name: Publish to TestPyPI via trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist-all/
